package praktikum8;

/**
 *
 * @author Syafiq
 */
public class Kalkulator extends javax.swing.JFrame {
    private String angka = "";
    private double total, angkaPertama, angkaKedua;
    private String operasi;

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKalkulator = new javax.swing.JPanel();
        panelAngka = new javax.swing.JPanel();
        tombol7 = new javax.swing.JButton();
        tombol8 = new javax.swing.JButton();
        tombol9 = new javax.swing.JButton();
        tombol4 = new javax.swing.JButton();
        tombol5 = new javax.swing.JButton();
        tombol6 = new javax.swing.JButton();
        tombol1 = new javax.swing.JButton();
        tombol3 = new javax.swing.JButton();
        tombol2 = new javax.swing.JButton();
        tombolTitik = new javax.swing.JButton();
        tombolC = new javax.swing.JButton();
        tombol0 = new javax.swing.JButton();
        panelPerhitungan = new javax.swing.JPanel();
        buttonKurang = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonBagi = new javax.swing.JButton();
        buttonKali = new javax.swing.JButton();
        buttonSamaDengan = new javax.swing.JButton();
        buttonPersen = new javax.swing.JButton();
        tombolE = new javax.swing.JButton();
        tombolB = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));

        panelKalkulator.setBackground(new java.awt.Color(255, 204, 204));

        panelAngka.setBackground(new java.awt.Color(56, 116, 120));

        tombol7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol7.setText("7");
        tombol7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol7ActionPerformed(evt);
            }
        });

        tombol8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol8.setText("8");
        tombol8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol8ActionPerformed(evt);
            }
        });

        tombol9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol9.setText("9");
        tombol9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol9ActionPerformed(evt);
            }
        });

        tombol4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol4.setText("4");
        tombol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol4ActionPerformed(evt);
            }
        });

        tombol5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol5.setText("5");
        tombol5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol5ActionPerformed(evt);
            }
        });

        tombol6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol6.setText("6");
        tombol6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol6ActionPerformed(evt);
            }
        });

        tombol1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol1.setText("1");
        tombol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol1ActionPerformed(evt);
            }
        });

        tombol3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol3.setText("3");
        tombol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol3ActionPerformed(evt);
            }
        });

        tombol2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol2.setText("2");
        tombol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol2ActionPerformed(evt);
            }
        });

        tombolTitik.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombolTitik.setText(".");
        tombolTitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTitikActionPerformed(evt);
            }
        });

        tombolC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombolC.setText("C");
        tombolC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCActionPerformed(evt);
            }
        });

        tombol0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombol0.setText("0");
        tombol0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAngkaLayout = new javax.swing.GroupLayout(panelAngka);
        panelAngka.setLayout(panelAngkaLayout);
        panelAngkaLayout.setHorizontalGroup(
            panelAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAngkaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAngkaLayout.createSequentialGroup()
                        .addComponent(tombol7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAngkaLayout.createSequentialGroup()
                        .addComponent(tombol4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAngkaLayout.createSequentialGroup()
                        .addComponent(tombol1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAngkaLayout.createSequentialGroup()
                        .addComponent(tombolTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombol0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombolC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelAngkaLayout.setVerticalGroup(
            panelAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAngkaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelAngkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombol0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPerhitungan.setBackground(new java.awt.Color(56, 116, 120));

        buttonKurang.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonKurang.setText("-");
        buttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangActionPerformed(evt);
            }
        });

        buttonTambah.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonTambah.setText("+");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonBagi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonBagi.setText("/");
        buttonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBagiActionPerformed(evt);
            }
        });

        buttonKali.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonKali.setText("X");
        buttonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaliActionPerformed(evt);
            }
        });

        buttonSamaDengan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonSamaDengan.setText("=");
        buttonSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSamaDenganActionPerformed(evt);
            }
        });

        buttonPersen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonPersen.setText("%");
        buttonPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersenActionPerformed(evt);
            }
        });

        tombolE.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombolE.setText("E");
        tombolE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEActionPerformed(evt);
            }
        });

        tombolB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tombolB.setText("B");
        tombolB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPerhitunganLayout = new javax.swing.GroupLayout(panelPerhitungan);
        panelPerhitungan.setLayout(panelPerhitunganLayout);
        panelPerhitunganLayout.setHorizontalGroup(
            panelPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerhitunganLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerhitunganLayout.createSequentialGroup()
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerhitunganLayout.createSequentialGroup()
                        .addComponent(buttonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerhitunganLayout.createSequentialGroup()
                        .addComponent(buttonPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPerhitunganLayout.createSequentialGroup()
                        .addComponent(tombolB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombolE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelPerhitunganLayout.setVerticalGroup(
            panelPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerhitunganLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelPerhitunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        hasil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hasil.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Kalkulator Sederhana");

        javax.swing.GroupLayout panelKalkulatorLayout = new javax.swing.GroupLayout(panelKalkulator);
        panelKalkulator.setLayout(panelKalkulatorLayout);
        panelKalkulatorLayout.setHorizontalGroup(
            panelKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKalkulatorLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKalkulatorLayout.createSequentialGroup()
                        .addGroup(panelKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hasil)
                            .addGroup(panelKalkulatorLayout.createSequentialGroup()
                                .addComponent(panelAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(panelPerhitungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKalkulatorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(179, 179, 179))))
        );
        panelKalkulatorLayout.setVerticalGroup(
            panelKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKalkulatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPerhitungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAngka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelKalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelKalkulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void tombol7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol7ActionPerformed
        // TODO add your handling code here:
        angka += "7";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol7ActionPerformed

    private void tombol8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol8ActionPerformed
        // TODO add your handling code here:
        angka += "8";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol8ActionPerformed

    private void tombol9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol9ActionPerformed

    private void tombol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol4ActionPerformed

    private void tombol5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol5ActionPerformed
        // TODO add your handling code here:
        angka += "5";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol5ActionPerformed

    private void tombol6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol6ActionPerformed
        // TODO add your handling code here:
        angka += "6";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol6ActionPerformed

    private void tombol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol1ActionPerformed
        // TODO add your handling code here:
        angka += "1";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol1ActionPerformed

    private void tombol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol3ActionPerformed
        // TODO add your handling code here:
        angka += "3";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol3ActionPerformed

    private void tombol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol2ActionPerformed

    private void tombolTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTitikActionPerformed
        // TODO add your handling code here:
        angka += ",";
        hasil.setText(angka);
    }//GEN-LAST:event_tombolTitikActionPerformed

    private void tombolCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCActionPerformed
        // TODO add your handling code here:
        angka = "";
        angkaPertama = 0;
        angkaKedua = 0;
        total = 0;
        operasi = "";
        hasil.setText("");
    }//GEN-LAST:event_tombolCActionPerformed

    private void tombol0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
        hasil.setText(angka);
    }//GEN-LAST:event_tombol0ActionPerformed

    private void buttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKurangActionPerformed
        // TODO add your handling code here:
        if (angka.equals("")) {
            angka += "-";
            hasil.setText(angka);
        }else{
            angkaPertama = Double.parseDouble(angka);
            operasi = "-";
            angka = "";
            hasil.setText(angka);
        }

    }//GEN-LAST:event_buttonKurangActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        angkaPertama = Double.parseDouble(angka);
        operasi = "+";
        angka = "";
        hasil.setText(angka);
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBagiActionPerformed
        // TODO add your handling code here:
        angkaPertama = Double.parseDouble(angka);
        operasi = "/";
        angka = "";
        hasil.setText(angka);
    }//GEN-LAST:event_buttonBagiActionPerformed

    private void buttonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaliActionPerformed
        // TODO add your handling code here:
        angkaPertama = Double.parseDouble(angka);
        operasi = "X";
        angka = "";
        hasil.setText(angka);
    }//GEN-LAST:event_buttonKaliActionPerformed

    private void buttonSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSamaDenganActionPerformed
        // TODO add your handling code here:
        angkaKedua = Double.parseDouble(angka);
        switch(operasi) {
            case "+":
                total = angkaPertama + angkaKedua;
                break;
            case "-":
                total = angkaPertama - angkaKedua;
                break;
            case "X":
                total = angkaPertama * angkaKedua;
                break;
            case "/":
                total = angkaPertama / angkaKedua;
                if (operasi.equals("/") && angkaKedua == 0) {
                    hasil.setText("Error: Division by zero");
                    angka = "";
                    return;
                    }
                break;
            case "%":
                total = angkaPertama % angkaKedua;
                break;
        }
        if (total == (int) total) {
            hasil.setText(String.valueOf((int) total));
        }else{
            hasil.setText(String.valueOf(total));
        }
        angka = String.valueOf(total);
    }//GEN-LAST:event_buttonSamaDenganActionPerformed

    private void buttonPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersenActionPerformed
        // TODO add your handling code here:
        angkaPertama = Double.parseDouble(angka);
        operasi = "%";
        angka = "";
        hasil.setText(angka);
    }//GEN-LAST:event_buttonPersenActionPerformed

    private void tombolEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEActionPerformed
        // TODO add your handling code here:
        angka = String.valueOf(Math.E);
        hasil.setText(angka);
    }//GEN-LAST:event_tombolEActionPerformed

    private void tombolBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBActionPerformed
        // TODO add your handling code here:
        //B digunakan untuk menghapus atau backspace
        if (angka.length() > 0) {
            angka = angka.substring(0, angka.length() - 1);
            hasil.setText(angka);
        }
    }//GEN-LAST:event_tombolBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBagi;
    private javax.swing.JButton buttonKali;
    private javax.swing.JButton buttonKurang;
    private javax.swing.JButton buttonPersen;
    private javax.swing.JButton buttonSamaDengan;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelAngka;
    private javax.swing.JPanel panelKalkulator;
    private javax.swing.JPanel panelPerhitungan;
    private javax.swing.JButton tombol0;
    private javax.swing.JButton tombol1;
    private javax.swing.JButton tombol2;
    private javax.swing.JButton tombol3;
    private javax.swing.JButton tombol4;
    private javax.swing.JButton tombol5;
    private javax.swing.JButton tombol6;
    private javax.swing.JButton tombol7;
    private javax.swing.JButton tombol8;
    private javax.swing.JButton tombol9;
    private javax.swing.JButton tombolB;
    private javax.swing.JButton tombolC;
    private javax.swing.JButton tombolE;
    private javax.swing.JButton tombolTitik;
    // End of variables declaration//GEN-END:variables
}
